apiVersion: v1
kind: Namespace
metadata:
  name: ml-experiments
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ml-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-storage-secret
    secretNamespace: ml-experiments
    shareName: ml-data
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-data-pvc
  namespace: ml-experiments
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: ml-data-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ml-output-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-storage-secret
    secretNamespace: ml-experiments
    shareName: ml-output
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-output-pvc
  namespace: ml-experiments
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: ml-output-pv
  storageClassName: ""